name: ufrmath env
# channels priority
# conda-forge has highest priority
channels:
  - defaults
  - conda-forge
dependencies:
  # Jupyter dependencies
  - jupyterhub>=1.5,<2
  - jupyterlab>=3.2,<4
  - jupyterlab-topbar
  # Python environment
  - python>=3.9
  - pip
